### ISSUE TITLE
Where are "pos.txt" "neg.txt" "neu.txt" ?

### ISSUE THREAD

**Issue by intuwat01** [PyThaiNLP/wisesight-sentiment#1]
Where are "pos.txt" "neg.txt" "neu.txt" for this copus to run in classification.ipynb.
I want to use it to see how to implement this corpus to my senior project.
If you want to contact me. Please use this address : Intuwat.siri@gmail.com
My name is : Intuwat Sirisangsawang (Thammasat Student)

**Comment by cstorm125** [comment]
.txt files are replaced by the csvs within the zip
